"""add price_daily and risk_free_series tables

Revision ID: a8acd71803f4
Revises: aa097a018895
Create Date: 2025-11-17 09:39:07.494598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8acd71803f4'
down_revision: Union[str, None] = 'aa097a018895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_free_series',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_free_series_date'), 'risk_free_series', ['date'], unique=True)
    op.create_table('price_daily',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('avg_volume', sa.BigInteger(), nullable=True),
    sa.Column('pe', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', name='uq_price_daily_ticker_date')
    )
    op.create_index(op.f('ix_price_daily_date'), 'price_daily', ['date'], unique=False)
    op.create_index(op.f('ix_price_daily_ticker_id'), 'price_daily', ['ticker_id'], unique=False)
    op.drop_table('portfolio_transaction')
    op.drop_table('portfolio_cash_ledger')
    op.add_column('portfolio', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('portfolio', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('portfolio', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('portfolio', 'initial_value',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('portfolio', 'cash',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('portfolio', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # Step 1: Add nullable ticker_id column first
    op.add_column('portfolio_holding', sa.Column('ticker_id', sa.UUID(), nullable=True))
    
    # Step 2: Migrate data from symbol to ticker_id by joining with ticker table
    op.execute("""
        UPDATE portfolio_holding ph
        SET ticker_id = t.id
        FROM ticker t
        WHERE t.symbol = ph.symbol
    """)
    
    # Step 3: Make ticker_id NOT NULL now that it has data
    op.alter_column('portfolio_holding', 'ticker_id', nullable=False)
    
    # Step 4: Add other new columns
    op.add_column('portfolio_holding', sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('portfolio_holding', sa.Column('average_cost', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('portfolio_holding', sa.Column('added_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    
    # Step 5: Copy data from old columns to new columns
    op.execute("UPDATE portfolio_holding SET shares = qty WHERE shares IS NULL")
    op.execute("UPDATE portfolio_holding SET average_cost = avg_cost WHERE average_cost IS NULL")
    
    # Step 6: Make shares NOT NULL
    op.alter_column('portfolio_holding', 'shares', nullable=False)
    
    # Step 7: Drop old constraint and columns
    op.drop_constraint('uq_portfolio_symbol', 'portfolio_holding', type_='unique')
    op.drop_column('portfolio_holding', 'symbol')
    op.drop_column('portfolio_holding', 'qty')
    op.drop_column('portfolio_holding', 'as_of')
    op.drop_column('portfolio_holding', 'avg_cost')
    
    # Step 8: Create new indexes and constraints
    op.create_index(op.f('ix_portfolio_holding_portfolio_id'), 'portfolio_holding', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_holding_ticker_id'), 'portfolio_holding', ['ticker_id'], unique=False)
    op.create_unique_constraint('uq_portfolio_ticker', 'portfolio_holding', ['portfolio_id', 'ticker_id'])
    op.create_foreign_key(None, 'portfolio_holding', 'ticker', ['ticker_id'], ['id'], ondelete='CASCADE')
    op.add_column('watchlist', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('watchlist', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('watchlist', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('watchlist', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # Step 1: Add nullable ticker_id column first
    op.add_column('watchlist_tickers', sa.Column('ticker_id', sa.UUID(), nullable=True))
    
    # Step 2: Migrate data from symbol to ticker_id by joining with ticker table
    op.execute("""
        UPDATE watchlist_tickers wt
        SET ticker_id = t.id
        FROM ticker t
        WHERE t.symbol = wt.symbol
    """)
    
    # Step 3: Make ticker_id NOT NULL now that it has data
    op.alter_column('watchlist_tickers', 'ticker_id', nullable=False)
    
    # Step 4: Drop old symbol column
    op.drop_column('watchlist_tickers', 'symbol')
    
    # Step 5: Update added_at column type
    op.alter_column('watchlist_tickers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    
    # Step 6: Create foreign key constraint
    op.create_foreign_key(None, 'watchlist_tickers', 'ticker', ['ticker_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_tickers', sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'watchlist_tickers', type_='foreignkey')
    op.alter_column('watchlist_tickers', 'added_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('watchlist_tickers', 'ticker_id')
    op.alter_column('watchlist', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('watchlist', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('watchlist', 'updated_at')
    op.drop_column('watchlist', 'description')
    op.add_column('portfolio_holding', sa.Column('avg_cost', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.add_column('portfolio_holding', sa.Column('as_of', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False))
    op.add_column('portfolio_holding', sa.Column('qty', sa.NUMERIC(precision=24, scale=6), autoincrement=False, nullable=False))
    op.add_column('portfolio_holding', sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'portfolio_holding', type_='foreignkey')
    op.drop_constraint('uq_portfolio_ticker', 'portfolio_holding', type_='unique')
    op.drop_index(op.f('ix_portfolio_holding_ticker_id'), table_name='portfolio_holding')
    op.drop_index(op.f('ix_portfolio_holding_portfolio_id'), table_name='portfolio_holding')
    op.create_unique_constraint('uq_portfolio_symbol', 'portfolio_holding', ['portfolio_id', 'symbol'])
    op.drop_column('portfolio_holding', 'added_at')
    op.drop_column('portfolio_holding', 'average_cost')
    op.drop_column('portfolio_holding', 'shares')
    op.drop_column('portfolio_holding', 'ticker_id')
    op.alter_column('portfolio', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('portfolio', 'cash',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('portfolio', 'initial_value',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('portfolio', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('portfolio', 'updated_at')
    op.drop_column('portfolio', 'description')
    op.create_table('portfolio_cash_ledger',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('portfolio_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='portfolio_cash_ledger_pkey')
    )
    op.create_table('portfolio_transaction',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('portfolio_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ticker_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('side', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('remaining_cash', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='portfolio_transaction_pkey')
    )
    op.drop_index(op.f('ix_price_daily_ticker_id'), table_name='price_daily')
    op.drop_index(op.f('ix_price_daily_date'), table_name='price_daily')
    op.drop_table('price_daily')
    op.drop_index(op.f('ix_risk_free_series_date'), table_name='risk_free_series')
    op.drop_table('risk_free_series')
    # ### end Alembic commands ###













